##Plugin made by crepppy.
##Version 1.0

#Commands all party players will do if the leader does them (joining games are done silently via command)
#Just the beginning of the command is needed without '/'
commands:
- mptp

##When these commands are run by console using the leader of the party as an argument, everyone in their party will have the command for them
console-commands:
- mvtp %player%

#List of discord users and players that have their discord's linked
linked-accounts: []

#Discord bot token for the /party discord command.
token: ''

#Lobby for players to join so they can get moved upon doing /party discord
discord-party-lobby: 0